name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  # Fonts And Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Logger
  logger: ^2.0.2

  # Database And Cache
  shared_preferences: ^2.0.15
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1

  # State Management
  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^2.0.4
  riverpod: ^2.1.3
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.20.1
  riverpod_state: ^0.1.1

  # Models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  retrofit: '>=4.0.0 <5.0.0'

  # Routing
  go_router: ^14.1.4
  responsive_framework: ^1.0.0
  dio: ^5.0.1

  # UI
  flutter_svg: ^2.0.2
  
  # Animations
  animated_text_kit: ^4.2.2
  

  # Utils
  gap: ^3.0.0
  form_validator: ^2.1.1
  since_date: ^0.0.2
  infinite_scroll_pagination: ^4.0.0
  image_picker: ^1.0.4
  awesome_dio_interceptor: ^1.0.0
  url_launcher: ^6.1.10
  skeletons: ^0.0.3
  cached_network_image: ^3.2.3
  image_cropper: ^6.0.0
  timeago: ^3.4.0
  country_code_picker: ^3.0.0
  # ffmpeg_kit_flutter: ^6.0.2

  path_provider: any
  flutter_kurdish_localization: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  # isar_generator: ^3.1.0+1
  custom_lint:
  riverpod_lint: ^2.0.4
  go_router_builder: any
  retrofit_generator: ^8.0.4
  build_runner: any
  flutter_gen_runner: any
  build_verify: any
  riverpod_generator: ^2.1.6
  flutter_lints: ^4.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  change_app_package_name: ^1.1.0
flutter_assets:
  assets_path: assets/
  output_path: lib/utils/constants/
  filename: assets.dart
  

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/videos/
